Also check for staged but uncommitted changes

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -12,20 +12,22 @@ RELEASE_BUILD="$ROOT/resources/release"
 VERSION=$(cut -d'"' -f2 < "$ROOT/config.edn")
 PACKAGE_DIR="$RELEASES/yank-$VERSION"
 
-if [[ $(git diff --stat) != '' ]]; then
+if ! git diff-index --quiet HEAD --; then
   echo >&2 'There are uncommitted changes, Aborting.'
   exit 1
 fi
 
 hash clj 2>/dev/null || {
-  echo >&2 "Clojure not installed.  Aborting."
+  echo >&2 "Clojure not found.  Aborting."
   exit 1 
 }
 
 hash npm 2>/dev/null || {
-  echo >&2 "NPM not installed.  Aborting."
+  echo >&2 "NPM not found.  Aborting."
   exit 1 
 }
+
+script/clean
 
 npm install
 
