Check for clj and clojure. Include npm install

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -13,9 +13,21 @@ VERSION=$(cut -d'"' -f2 < "$ROOT/config.edn")
 PACKAGE_DIR="$RELEASES/yank-$VERSION"
 
 if [[ $(git diff --stat) != '' ]]; then
-  echo >&2 'There are uncommitted changes, exiting.'
+  echo >&2 'There are uncommitted changes, Aborting.'
   exit 1
 fi
+
+hash clj 2>/dev/null || {
+  echo >&2 "Clojure not installed.  Aborting."
+  exit 1 
+}
+
+hash npm 2>/dev/null || {
+  echo >&2 "NPM not installed.  Aborting."
+  exit 1 
+}
+
+npm install
 
 clj -A:html
 clj -A:manifest
